### ISSUE TITLE
When will the code be uploaded?

### ISSUE THREAD

**Issue by bibekyess** [megapose6d/megapose6d#1]
Hello! Thank you for the awesome work. Can I know when the codes be available for public?

**Comment by ylabbe** [comment]
Hi, thanks for the interest if our work! We have the code ready and we are just waiting for some internal legal approval to get it released. It should be hopefully be fairly quick. I will provide more information on the timeline whenever i get more information.

**Comment by ylabbe** [comment]
We are planning to release on January 9th.

**Comment by bibekyess** [comment]
Great! Thank you for your response!!

**Comment by ylabbe** [comment]
The code has been released :)
