### ISSUE TITLE
bop_toolkit_lib missing

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [megapose6d/megapose6d#3]
Hi, 

Thanks for the release, it looks like a very promising project.
I am trying the inference code and hit `ERROR: No matching distribution found for bop_toolkit_lib`
I found it on Github but figured I should let you know,

Cheers,
Thibault

**Comment by manuelli** [comment]
That package is a submodule, see #4. You just need to run

```
git submodule update --init
```

from inside the repo.
