### ISSUE TITLE
Is the synthetic dataset generation pipeline script available?

### ISSUE THREAD

**Issue by dingdingcai** [megapose6d/megapose6d#33]
Hi, 

Thanks for sharing the excellent work!

Is the source code (script) for rendering the photorealistic images used in this project available?

Thanks!

**Comment by hoenigpeter** [comment]
Hi,

I would also appreciate if you could share the blenderproc files to render the dataset!

Thanks!

**Comment by taeyeopl** [comment]
Hi @dingdingcai @hoenigpeter @ylabbe,

Do I have a chance to get the GSO data generation scripts?
