### ISSUE TITLE
404 on inference tutorial : pose estimation models & example data urls

### ISSUE THREAD

**Issue by xieyizheng** [megapose6d/megapose6d#35]
Hi! 

Thanks for the excellent work!

I notice that two download url links for the inference tutorial section can't be reached anymore:

> Inference tutorial
We provide a tutorial for running inference on an image with a novel object. You can adapt this tutorial to your own example.

>1. Download pre-trained pose estimation models
Pose estimation models are available at this [url](https://drive.google.com/drive/folders/1c3z8IkyIUThYxTU7CIs4QJ3kvD0RkyCz). You can download it using rlcone:

>cd $MEGAPOSE_DATA_DIR
rclone copyto inria_data:megapose-models/ megapose-models/ --exclude="**epoch**" --config $MEGAPOSE_DIR/rclone.conf -P
>2. Download example data
In this tutorial, we estimate the pose for a barbecue sauce bottle (from the [HOPE](https://github.com/swtyree/hope-dataset) dataset, not used during training of MegaPose). We start by downloading the inputs necessary to MegaPose for this tutorial (you can also use this [link](https://drive.google.com/drive/folders/10BIvhnrKGbNr8EKGB3KUtkSNcp460k9S)):

**Comment by lingxiaomeng** [comment]
I had the same problem.

**Comment by ylabbe** [comment]
This is fixed now
