### ISSUE TITLE
About caching renders

### ISSUE THREAD

**Issue by saishruthibalaji** [megapose6d/megapose6d#40]
I'm trying to implement the caching of renders since it's the most time consuming part of the pipeline. I see renderings being created in the [refiner](https://github.com/megapose6d/megapose6d/blob/419a167ad9888d5a6a79a182f21424168a4b8e15/src/megapose/models/pose_rigid.py#L555) as well as the [coarse estimator](https://github.com/megapose6d/megapose6d/blob/419a167ad9888d5a6a79a182f21424168a4b8e15/src/megapose/models/pose_rigid.py#L689). Why not reuse the renders made during coarse estimation. Why is it being done twice? Am I understanding this wrong?

**Comment by TrinhNC** [comment]
I think they explained this in the Figure 2 in the [paper](https://arxiv.org/pdf/2212.06870.pdf). "Given a cropped input image the coarse module renders the object in multiple input poses" and "Given an initial pose estimate, the refiner renders the objects at
the estimated pose along with 3 additional viewpoints". I'm wondering is it possible to save the renders to a file and reuse it (at least for the coarse pose)? Have you tried that?

**Comment by saishruthibalaji** [comment]
Hi @TrinhNC , Thanks for clarifying. I was able to implement caching for the coarse renders like you said. But for the refiner, since it's dependent on the pose chosen by the coarse predictor, would this be deterministic? There are also multiple iterations for the refiner, so for each iteration, the renders will be different right? Does it even make sense to implement caching for the refiner?

**Comment by TrinhNC** [comment]
Hi @saishruthibalaji , good to know that you alread implemented it. Does it run faster than before? I don't think we should do it for the refiner because, also like you said, it depends on the coarse pose and since it only renders 4 view, the rendering should be fast. For the coarse pose I also found out that they use the bboxes information to randomize the rendered poses so it would not stay the same. Another idea, was also mentioned in the paper, is to try out another coarse pose methods.

**Comment by saishruthibalaji** [comment]
@TrinhNC Like you said, the cached coarse renders worked when I used them for multiple objects in the same scene with similar bounding boxes. Example:

Detections:
![detections](https://github.com/megapose6d/megapose6d/assets/106185420/345c249d-127e-4a3c-bbcd-ffcfa6776421)

Results:
![all_results](https://github.com/megapose6d/megapose6d/assets/106185420/f096395e-0015-4a5f-8cc1-3e1455d019f2)

But when there is variation in the scene and scale of the bounding boxes, I could not reuse the coarse renders. When I used the above coarse renders in the below scene, the results were bad:

![all_results](https://github.com/megapose6d/megapose6d/assets/106185420/0dc0dcf5-0e4b-444c-9a18-9849d52c2461)

Do you recommend any other way of speed-ups here?

[P.S. I really have to say that this is a great project and it's crazy how well this works for any new part. Thank you for this work!]

**Comment by TrinhNC** [comment]
@saishruthibalaji right now I can only think of one way is to use another package for coarse pose estimation. This was also mentioned in the paper. But then we need to create training data.

**Comment by saishruthibalaji** [comment]
Thank you!

**Comment by CQUChenC** [comment]
Hello, I would like to ask how much the inference speed can improve after adding caching. Have you conducted any experiments on this?
