### ISSUE TITLE
module 'pinocchio' has no attribute 'SE3'

### ISSUE THREAD

**Issue by 2021270902001sc** [megapose6d/megapose6d#65]
![1 0 HV0X@V6DYZ4TW9R3B8](https://github.com/megapose6d/megapose6d/assets/118178618/0d2099ce-d5f2-4be9-9e15-c6c0b3bc486a)
![9T8PP7NF1RFL )N 36YJHIY](https://github.com/megapose6d/megapose6d/assets/118178618/ea396b19-c2d1-45ab-93ff-f84ae3aca17a)
I don't know why the installed Pinocchio library does not have the attribute 'SE3'.
I even reinstalled Pinocchio using the Pip package installation method mentioned on the official website（https://auctus-team.gitlabpages.inria.fr/people/antunskuric/pycapacity/examples/pinocchio.html）.

**Comment by 2021270902001sc** [comment]
I think this should be an issue with the official Pinocchio library. I saw the same issues on their GitHub repository.
![image](https://github.com/megapose6d/megapose6d/assets/118178618/64ffc5c7-5776-4368-888a-8d6b889399df)

**Comment by 2021270902001sc** [comment]
Oh, shit. I mistook the project on PyPI as the same one. They don't belong to the same project. I'm really sorry.

**Comment by CQUChenC** [comment]
@2021270902001sc Hi, I encountered the same issue: AttributeError: module 'pinocchio' has no attribute 'SE3'. My pinocchio version is 0.4.3. Have you resolved it?

**Comment by 2021270902001sc** [comment]
请不要直接pip install pinocchio,请用pip install pin
这个官方项目链接地址，由于该包名被另一项目提前注册，导致在pypi上不得不改名
https://github.com/stack-of-tasks/pinocchio
祝你项目顺利

**Comment by 2021270902001sc** [comment]
> 嗨，我遇到了同样的问题：AttributeError：模块“pinocchio”没有属性“SE3”。我的 Pinocchio 版本是 0.4.3。您解决了吗？
请不要直接pip install pinocchio，请用pip install pin

**Comment by CQUChenC** [comment]
@2021270902001sc 你好，我主要研究位姿估计方向，可否加个好友互相交流，共同学习，微信：13364002090，等你加了我就删除这条消息。
