### ISSUE TITLE
Questions about megapose dataset

### ISSUE THREAD

**Issue by parkjaewoo0611** [megapose6d/megapose6d#8]
Hi, thanks for releasing this high-quality dataset.

I'm trying to use your dataset to train the network, and I have two questions about how to use it.

First, I tried to project the 3d bounding box to the image to check whether the ground truth pose matches to appearance.

As you used the combination of the inverse of TWC and TWO as pose ground truth (in pose_dataset.py 308 line), I followed the same way and projected the 3d bounding box to the image.

However, the result shows a scale issue and does not match the bbox_amodal in the JSON file, where the red box shows the amodal bbox from JSON and blue lines show part of the projected 3d bbox (which is too close to the camera).

Is there any scale parameter for translation that I should consider? 

Here is my code snippet to check the google scanned dataset you released and the projection result.

![snippet](https://user-images.githubusercontent.com/26773195/213867141-e8309fe6-6f78-4949-8c3e-2e9d97c4e8c5.png)

Second, I found four versions of mesh files in your dataset. (models_bop-renderer_scale=0.1, models_normalized, models_orig, models_pointcloud) Which version should be used with twc, two in JSON file? (In the snippet, I used models from 'models_normalized' to generate a 3d bounding box).

Any help would be appreciated.

**Comment by m13ammed** [comment]
Did you find a solution for this? 

I am as well trying to do something similar
