### ISSUE TITLE
shapenetcorev2 - Download quota exceeded for this file

### ISSUE THREAD

**Issue by monajalal** [megapose6d/megapose6d#9]
I am trying to download the shapenetcorev2 required by the notebook but I get the error as shown in the screenshot. Do you have any workaround for this?

![Screenshot from 2023-01-23 13-28-16](https://user-images.githubusercontent.com/1892917/214120475-f2683240-c3b0-4f3e-ada6-a7c85a2a655e.png)
https://drive.google.com/drive/folders/1AYxkv7jpDniOnTcMAxiWbdhPo8WBJaZG

![Screenshot from 2023-01-23 13-29-56](https://user-images.githubusercontent.com/1892917/214120628-4b367bea-b45c-4768-a179-8590c295a7b5.png)

**Comment by monajalal** [comment]
Hi just checking again to see if you could please provide a solution?

**Comment by Kowndinya2000** [comment]
Hi, you can very well download the `shapenetcorev2.zip` dataset by using `rclone` command (check readme). `rclone` is capable of `resumable file transfers`, meaning to say if the download operation gets broken, by running `rclone` again, we can resume the process without starting over again. 
I am referring to this part in the readme:
`rclone copyto megapose_public_readonly:/tars tars/ --include "shapenetcorev2.zip" --include "google_scanned_objects.zip" --config $MEGAPOSE_DIR/rclone.conf -P`

I was able to download it successfully, but the size of this zip file is around 133GB though.
